<?php
require_once __DIR__ . '/vendor/autoload.php';

function smartcat_translation_manager_install() {
}

function smartcat_translation_manager_uninstall() {
    $state = \Drupal::state();
    $state->set('smartcat_api_login', '');
    $state->set('smartcat_api_password', '');
}

function smartcat_translation_manager_enable() {
}

function smartcat_translation_manager_disable() {
}

function smartcat_translation_manager_schema() {
    return \Drupal\smartcat_translation_manager\Helper\SchemaHelper::getSchemas();
}

