<?php

/**
 * @file for initial module
 */

use Drupal\smartcat_translation_manager\CronHandler;
use Drupal\Core\Entity\EntityInterface;
use Drupal\smartcat_translation_manager\Event\EntityEvent;

require_once __DIR__ . '/vendor/autoload.php';

define('SMARTCAT_PLUGIN_FILE', __FILE__);
define('SMARTCAT_PLUGIN_NAME', 'smartcat_translation_manager');

define(
  'SMARTCAT_PLUGIN_DIR',
  realpath(pathinfo(__FILE__, PATHINFO_DIRNAME)) . DIRECTORY_SEPARATOR
);

/**
 * Implements hook_entity_insert
 */
function smartcat_translation_manager_entity_insert(EntityInterface $entity) {
  \Drupal::service('event_dispatcher')->dispatch(EntityEvent::ENTITY_INSERT, new EntityEvent($entity));
}

/**
 * Implements hook_entity_update
 */
function smartcat_translation_manager_entity_update(EntityInterface $entity) {
  \Drupal::service('event_dispatcher')->dispatch(EntityEvent::ENTITY_UPDATE, new EntityEvent($entity));
}

/**
 * Implements hook_entity_delete
 */
function smartcat_translation_manager_entity_delete(EntityInterface $entity) {
  \Drupal::service('event_dispatcher')->dispatch(EntityEvent::ENTITY_DELETE, new EntityEvent($entity));
}

/**
 * Implements hook_cron
 */
function smartcat_translation_manager_cron() {
  $cronHandler = CronHandler::create();

  if ($cronHandler !== NULL) {
    $cronHandler->run();
  }
}

/**
 * Implements hook_page_attachments_alter
 */
function smartcat_translation_manager_page_attachments_alter(array &$page) {
  $page['#attached']['library'][] = 'smartcat_translation_manager/smartcat_base';

}
