<?php
require_once __DIR__ . '/inc/autoload.php';

function translation_connectors_install() {
}

function translation_connectors_uninstall() {
  \SmartCAT\Drupal\Connector::plugin_uninstall();
}

function translation_connectors_enable() {
  $connector   = new \SmartCAT\Drupal\Connector();
  $connector->plugin_activate();
}

function translation_connectors_disable() {
  $connector   = new \SmartCAT\Drupal\Connector();
  $connector->plugin_deactivate();
}